### ISSUE TITLE
Switch to jsone for JSON

### ISSUE THREAD

**Issue by meppu** [esl/rebar3_codecov#8]
I think it would be a good idea to start using a pure Erlang approach for handling JSON. The only downside I can see is it might be slightly slower. However, in this particular case, the speed difference wouldn't have much impact. But still, that's another reason why I chose [jsone](https://github.com/sile/jsone) over [jsx](https://github.com/talentdeficit/jsx).

On the other hand, by switching to a pure Erlang approach instead of using jiffy would ensure compatibility across Erlang environments and eliminate the need to compile a NIF for it.

If you're interested, I can create a pull request.

**Comment by arcusfelis** [comment]
Hi,

Sure, you could prepare.
Just use a hex package...

Generating json is pretty quick, getting deps is slower usually.
But on CI we cache built libs.
Also, we use jiffy a lot in other projects.

We can still consider it, so make a PR :)

**Comment by meppu** [comment]
Closing this as completed since pull-request is merged :)
